### PR TITLE
Update num2bin.c

### PR DESCRIPTION
**Pull request by milahu**
replace the conversion table with encode/decode functions

#TODO please someone test this code
i just found this code from year 2011 ....
i lost all my climate logger sticks
and im too lazy to write a test script
to compare the old conversion table and the new functions
but i trust my code : P

#TODO move all the code to vdl120.c

### CODE REVIEW

**Comment by kollokollo** [comment]
Thank you.

**Comment by milahu** [comment]
i made a [test script](https://github.com/milahu/random/blob/master/vdl120/test_num2bin.c) now

the functions do work in theory
but i seem to have a problem with byte order (endianness)

the num2bin functions from the pull request
seem to use the wrong byte order

a quickfix (to change byte order)
is included in the test script:

```
// TODO byte order
	//pbin[0] = (sign << 7) + ((firstBit + 127) >> 1);
	//pbin[1] = (((firstBit + 127) & 1) << 7) + ((num - (1 << firstBit)) << (7-firstBit));
	// change byte order
	pbin[1] = (sign << 7) + ((firstBit + 127) >> 1);
	pbin[0] = (((firstBit + 127) & 1) << 7) + ((num - (1 << firstBit)) << (7-firstBit));

	return bin;
}

short int bin2num(short int bin)
{
	char *pbin = NULL;

// TODO byte order
	//pbin = (char *) &bin;
	// change byte order
	pbin = malloc(2 * sizeof(char)); // free(pbin) later
	pbin[0] = ( (char *) &bin )[1];
	pbin[1] = ( (char *) &bin )[0];

	// ....

	free(pbin);
	return num;
```


please test the code with a climate logger

**Comment by kollokollo** [comment]
What about this algorithm: (independant of byte ordering) taken from USBDataloggerreader-Android:
`
short num2bin(float af) {
		boolean f=false;
		short ret=0;
		int a = (int)af;
		if(a<0) {a=-a;f=true;}
		if(a==0) return 0;
		else if(a==1) ret=0x3f80;
		else if(a==2) ret=0x4000;
		else if(a<=4) ret= (short) ((short)0x4000+((a-2)<<6));
		else if(a<=8) ret= (short) ((short)0x4080+((a-4)<<5));
		else if(a<=16) ret= (short) ((short)0x4100+((a-8)<<4));
		else if(a<=32) ret= (short) ((short)0x4180+((a-16)<<3));
		else if(a<=64) ret= (short) ((short)0x4200+((a-32)<<2));
		else ret= (short) ((short)0x4280+((a-64)<<1));
		if(f) ret=(short) (ret&0x8000);
		return ret;
	} 
`

**Comment by milahu** [comment]
yes! that is helpful

that "bin2num udlr" function
is also much faster with O(log(n))
than the old "bin2num table" function with O(n)

but its still not perfect : P

my current version "bin2num udlr switch"
runs in O(1) = constant time
and is faster than "bin2num udlr" by factor 2.5

the trick is to
use an optimized switch statement
with consecutive numbers
so the compiler can use a "jump table"

```
#include <stdbool.h>

// use switch statement, instead of if-else branches
int bin2num_udlr_switch(short b) {

	if (b == 0)
		return 0;

	int n = 4711; // TODO why? error code?
	bool sn = (b<0); // negative sign
	// 0 for positive n
	// 1 for negative n
	
	b &= 0x7fff; // set sign bit to zero

	short h = b >> 7; // hash value = high bits
	switch (h) {
		//case   0: n = 0; break; // this would slow the switch
		// switch is fastest with consecutive numbers
		// so compiler can use a jump table
		case 127: n = 1; break;
		case 128: n = ((b-0x4000)>>6)+ 2; break;
		case 129: n = ((b-0x4080)>>5)+ 4; break;
		case 130: n = ((b-0x4100)>>4)+ 8; break;
		case 131: n = ((b-0x4180)>>3)+16; break;
		case 132: n = ((b-0x4200)>>2)+32; break;
		case 133: n = ((b-0x4280)>>1)+64; break;
	}

	if (sn) n = -n;
	return n;
}
```

some benchmarks ....

times are in nanoseconds per single function call

test_num2bin 1564260928

zoom in:

test_num2bin 1564260928

**Comment by milahu** [comment]
oof, this is still embarassing.

i found the right solution only days later,
but for four months, i managed to ignore the issue ....

the solution is [bfloat16.c](https://stackoverflow.com/a/57259284/10440128)

> turns out, the "cryptic integer" format isnt cryptic at all ....
> 
> the format is bfloat16 aka brain float
> a truncated form of the 32bit float

> as expected, this is faster than the "switch" version [7 ns vs. 11 ns]
> 
> test_num2bin 1565633243
> 
> only slower than a "full table" lookup, without boundary checks:
> 
> ```
> int8_t bin2num_rtable_nocheck(uint16_t bin)
> {
> 	return bin2num_data[bin];
> }
> ```

> to handle endianness at runtime, we use function pointers.
> 
> to reduce overhead, we process a whole array in one function call.
> this also comes handy when processing raw data from hardware loggers.

```c
// convert between float32 and bfloat16
// public domain + no warranty

#include <stdint.h> // uint16_t, int8_t
#include <stdlib.h> // malloc, free, size_t
#include <string.h> // memset
#include <stdbool.h> // bool
#include <stdio.h> // printf



typedef uint16_t bfloat16; // --> "maybe remove"
typedef float     float32;



// stolen from tensorflow bfloat16.cc

void float32_to_bfloat16_be(float32 *src, bfloat16 *dst, size_t size)
{
    uint16_t *s = (uint16_t *)src;
    uint16_t *d = (uint16_t *)dst; // maybe remove

    for (; size != 0; s += 2, d++, size--) {
        // big endian byte order
        *d = s[0];
    }
}

void float32_to_bfloat16_le(float32 *src, bfloat16 *dst, size_t size)
{
    uint16_t *s = (uint16_t *)src;
    uint16_t *d = (uint16_t *)dst; // maybe remove

    for (; size != 0; s += 2, d++, size--) {
        // little endian byte order
        *d = s[1];
    }
}

void bfloat16_to_float32_be(bfloat16* src, float32* dst, size_t size)
{
    uint16_t *s = (uint16_t *)src; // maybe remove
    uint16_t *d = (uint16_t *)dst;

    for (; size != 0; s++, d += 2, size--) {
        // big endian byte order
        d[0] = *s;
        d[1] = 0;
    }
}

void bfloat16_to_float32_le(bfloat16* src, float32* dst, size_t size)
{
    uint16_t *s = (uint16_t *)src; // maybe remove
    uint16_t *d = (uint16_t *)dst;

    for (; size != 0; s++, d += 2, size--) {
        // little endian byte order
        d[0] = 0;
        d[1] = *s;
    }
}



// detect byte order at runtime
// http://esr.ibiblio.org/?p=5095#comment-415728
// this usually does not generate any code at all with GCC even with -O1
// ignore byte orders other than LE and BE

static inline bool is_big_endian() {
    const uint16_t endianness = 256; // 0b 00000001 00000000
    return *(const uint8_t *)&endianness;
}



// demo program

int main()
{
    // function pointers for the current byte order
    void (*float32_to_bfloat16)(float32*, bfloat16*, size_t) = NULL;
    void (*bfloat16_to_float32)(bfloat16*, float32*, size_t) = NULL;

    // detect byte order at runtime
    if (is_big_endian())
    {
        printf("byte order is big endian\n");

        float32_to_bfloat16 = &float32_to_bfloat16_be;
        bfloat16_to_float32 = &bfloat16_to_float32_be;
    }
    else
    {
        printf("byte order is little endian\n");

        float32_to_bfloat16 = &float32_to_bfloat16_le;
        bfloat16_to_float32 = &bfloat16_to_float32_le;
    }



    // convert one number

     float32 a1 = 3.1415;
    bfloat16 b1 = 0;

    float32_to_bfloat16(&a1, &b1, 1);



    bfloat16 a2 = 0x4049;
     float32 b2 = 0;

    bfloat16_to_float32(&a2, &b2, 1);



    printf("%1.4f --> 0x%04x\n", a1, b1);
    printf("%1.4f <-- 0x%04x\n", b2, a2);



    // convert many numbers

     float32 a3[2] = {2.7182, 1.4142};
    bfloat16 b3[2] = {0};

    float32_to_bfloat16(a3, b3, 2);



    bfloat16 a4[2] = {0x402d, 0x3fb5};
     float32 b4[2] = {0};

    bfloat16_to_float32(a4, b4, 2);



    printf("%1.4f --> 0x%04x\n", a3[0], b3[0]);
    printf("%1.4f <-- 0x%04x\n", b4[0], a4[0]);

    printf("%1.4f --> 0x%04x\n", a3[1], b3[1]);
    printf("%1.4f <-- 0x%04x\n", b4[1], a4[1]);

    return 0;
}
```

**Comment by milahu** [comment]
just uploaded my current version of [bfloat16.c](https://github.com/milahu/vdl120/blob/patch-2/src/bfloat16.c)
i want to keep it a separate file, so others can re-use it easier

in vdl120.c we can replace
`bin2num` to `int_from_bfloat16`
and
`num2bin` to `bfloat16_from_int`

.. and use the optimized function `bfloat16_to_float32` where possible

we must call `bfloat16_init` before using these functions

code not tested, since i have no hardware logger
at least it compiles with success

**Comment by kollokollo** [comment]
Ok, wow, good to know.

**Pull request merged**
